export const Paths = {
    landingPage: "/",
    signIn: "/sign-in",
    signUp: "/SignUp",
    home: "/home",
    about: "/about",
    contact: "/contact",
    dashboard: "/dashboard",
    calorieCalculator: "/mifflin-st-jeor-equation-calculator-for-nutrition",
    profile: "/profile",
    adminPage: "/admin/admin-panel",
    usersPage: "/admin/users-list",
    reviewsPage: "/admin/reviews-list",
    recommendRecipes: "/user/recipes-recommendation",
    notAuthorized: "/notAuthorized",
    notFound: "*",
    stockify: "/stockify",
    products : "/stockify/products",
    forgotPassword:"/forgotPassword",
    resetPassword: "/resetPassword",
    vats: "vats",   // relative should not be /vats
    addVat: "vats/add",
    categories:"categories",
    addCategory:"categories/add",
    clients:"clients",
    client:":id" ,
    addClient:"client/add",
    suppliers:"suppliers",
    addSupplier:"supplier/add",


  };