spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stockify_db?createDatabaseIfNotExist=true
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  #create-drop, update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  datasource:
#    primary:
#      jdbc-url: jdbc:postgresql://localhost:5432/stockify_db?createDatabaseIfNotExist=true
#      username: username
#      password: password
#      driver-class-name: org.postgresql.Driver
#  tenant:
#    datasource:
#      url-base: jdbc:postgresql://localhost:5432/tenant
#      username: username
#      password: password
#      driver-class-name: org.postgresql.Driver

#  mail:
#    host: localhost
#    port: 1025
#    username: ala
#    password: ala
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000


server:
  port: 8088