spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect #org.hibernate.dialect.PostgreSQLDialect
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/Stockify_Primary_DB?createDatabaseIfNotExist=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    multitenant:
      jdbc-url: jdbc:mysql://localhost:3306/Stockify_Default_Tenant_DB?createDatabaseIfNotExist=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  datasource:
#    primary:
#      jdbc-url: jdbc:postgresql://localhost:5432/multiTenantPrimary_dB?createDatabaseIfNotExist=true
#      username: username
#      password: password
#      driver-class-name: org.postgresql.Driver
#    multitenant:
#      jdbc-url: jdbc:postgresql://localhost:5432/multiTenantDefault_db?createDatabaseIfNotExist=true
#      username: username
#      password: password
#      driver-class-name: org.postgresql.Driver


#  mail:
#    host: localhost
#    port: 1025
#    username: ala
#    password: ala
#    properties:
#      mail:
#        smtp:
#          trust: "*"
#        auth: true
#        starttls:
#          enabled: true
#        connectiontimeout: 5000
#        timeout: 3000
#        writetimeout: 5000


server:
  port: 8088

database:
  default:
    pass: "0000"
    username: root

  tenant:
    prefix: jdbc:mysql://localhost:3306/Stockify_Tenant_

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - health
#          - info
#          - metrics
#          - loggers
#          - env

  endpoint:
    health:
      show-details: always