spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/prod_db
    username: prod_user
    password: prod_secure_password
  jpa:
    hibernate:
      ddl-auto: validate  # Only validate schema, no auto-update
    show-sql: false       # Disable SQL logging in production